# Change these first
owner: cmoriarty # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Jellyfin
    url: https://jellyfin.underthere.xyz
  - name: Jellyseerr
    url: https://jellyseerr.underthere.xyz
  - name: Bitwarden
    url: https://bitwarden.underthere.xyz
  - name: Immich
    url: https://immich.underthere.xyz


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.underthere.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://en.wikipedia.org/wiki/Strong_Bad#/media/File:Strong_Bad.png
  name: Status
  introTitle: "Status Monitor"
  introMessage: "Check here for status of services underthere ;)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
