# Change these first
owner: ChrisMoriarty # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Jellyfin
    url: https://jellyfin.underthere.xyz
    maxResponseTime: 3000
  - name: Jellyseerr
    url: https://jellyseerr.underthere.xyz
    maxResponseTime: 3000
  - name: Bitwarden
    url: https://bitwarden.underthere.xyz
    icon: https://bitwarden.underthere.xyz/favicon.ico
    maxResponseTime: 3000
  - name: Immich
    url: https://immich.underthere.xyz
    maxResponseTime: 3000
  - name: Mealie
    url: https://mealie.underthere.xyz
    maxResponseTime: 3000
  - name: Tandoor
    url: https://tandoor.underthere.xyz
    maxResponseTime: 3000
  - name: Vaultwarden
    url: https://vaultwarden.underthere.xyz
    maxResponseTime: 3000
  - name: Paperless
    url: https://paperless.underthere.xyz
    maxResponseTime: 3000
  - name: Audiobookshelf
    url: https://audiobookshelf.underthere.xyz
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.underthere.xyz
  favicon: https://art.pixilart.com/d4da25035ed0d2b.png
  assignees: # Users to assign downtime issues (optional)
  - ChrisMoriarty
  # baseUrl: /your-repo-name
  logoUrl: https://art.pixilart.com/d4da25035ed0d2b.png
  name: Upptime
  introTitle: "Hi."
  introMessage: "Realtime status monitoring for services underthere ;)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
